### ISSUE TITLE
Scripts that use the clock window are broken due to the addition of a 3rd line in tale 8

### ISSUE THREAD

**Issue by tizubythefizo** [DashingStrike/Automato-ATITD#104]
A third line was added in T8 to the clock window (Owned by: <FactionName>) and it seems all scripts that rely on it to work (flax, gather, etc...) fail with an error #55 Incorrect number of arguments for makePoint()

I'm guessing it's happening inside findCoords() but haven't been able to figure out how to debug/step into the code.

**Comment by Jimbly** [comment]
That might be in the native (non-LUA) code.  If so, you should be able to get and build Automato from source (with the free version of Visual Studio 2017) by grabbing the code from the SVN repository, some details here: https://github.com/DashingStrike/Automato/wiki#source-code  SVN repo is svn://www.dashingstrike.com/other/VeggieTales - I can set you up with write access or you can send me a .diff if you have a fix.

I didn't write the OCR code that I'm assuming you're referring to, and I doubt the author is still active in the community, so it might take a bit of digging =).

**Comment by tizubythefizo** [comment]
Actually I've found a temporary fix. It's line 18 of common_gps.inc (in Automato\games\common)

The line is 'local str = lines[#lines][2];' which is now returning the new line of "Owned By: <FactionName>"

I changed it to 'local str = lines[#lines - 1][2];' and it works perfectly (returning the coordinates as expected, and passing them in correctly to makePoint, where before they were passing in nil which caused the error).

I'd check it in but A) I'm not exactly sure how (I'm a TFS guy) and B) It's somewhat of a fragile fix, because there are places in the game where that third line isn't there (such as Welcome Island). So it would end up needing to handle both which, while somewhat simple, is a bit more than I'm comfortable doing since my knowledge of LUA is virtually 0.

**Comment by Jimbly** [comment]
I doubt anyone is running scripts on the Welcome Island, so I wouldn't worry about that too much.  Simplest way to make the change if you're not familiar with Git is to use the web interface, just go here: https://github.com/DashingStrike/Automato-common/blob/master/scripts/common_gps.inc click the edit icon, make the change, and it'll submit a "pull request".  I haven't played ATITD since before T5, before these particular scripts were made, and there are no active scripters playing that I know of (but still a bunch of people using the macros), so I'll accept any PRs in good faith =).

**Comment by Jimbly** [comment]
Merged your fix in https://github.com/DashingStrike/Automato-common/pull/18 , I believe this should be fixed now, thanks for your help!
