### ISSUE TITLE
Vinetender_Gyges.lua interprets value incorrectly

### ISSUE THREAD

**Issue by Jimbly** [DashingStrike/Automato-ATITD#77]
Submitter: Amunsul
Email: amunsul@gmail.com
when running this macro to tend my grapevines, it does an excellent job determining how much vigor is left and therefor whether the vine can survive the preferred tend i have saved. However, when the vigor gets to the 20's (ie 20-29) it ALWAYS says that the vine lacks the vigor to be tended anymore and as such is ready to be harvested. I know the preferred tend i have saved for that vine status doesn't cost 20+ vigor, so it shouldn't be jumping to that status. Furthermore, if i manually tend the vine to the point where the vine is <20, the macro starts working again and will tend the vine successfully until the vigor is low enough that it REALLY wont survive my preferred tends vigor cost. This only occurs when the Vigor stat is in the 20's, otherwise no other issues. I have spoken to others who use this macro and none of them have this issue. I have tried copying the macro from one of them to see if my copy was just defunct, but no luck. This also occurs when i use the original VineTender.lua macro that wasn't altered by Gyges. Any help would be greatly appreciated. If not for this issue i would use the hell out of this macro! Thanks!

**Comment by Viracoocha** [comment]
Hiya!  I have spoken with Amunsul in game about this since his posting.  I too have the same issues.  With original and the Gyges.lua.  I have found, it is not just 20-29, but the singular 2 also.  A real value of a leading 2 on screen seems to return 0 for vigor.  We know vigor cant really be at 0 or the grapes would be dead.  I made a slight alteration to when the vigor variable is assigned, to say basically, if vigor = 0, then vigor = 20.  It will never take more off that would kill the crop.  OTHER than when vigor is JUST 2. so, it works through the 20's for you no problem, just reports still 0 vigor after the tend till you get udner 20 again.  

Now, I started tending some of my guildmates vines, and DO NOT have this issue.  The difference I have found with theirs, is that they are not abutting each other like mine.  and from speaking with amunsul, I believe his are abutting.  I dont know how that can affect the screen read through.  I have built a few non abutting vineyards, and am waiting to get into the 20's with them to see if I have that problem.  

so:  My current vineyards are built like this......


|++++||++++||++++|
|++++||++++||++++|
|++++||++++||++++|


now I have done some like this for testing:

|++++|   |++++|   |++++|

|++++|   |++++|   |++++|

|++++|   |++++|   |++++|

**Comment by Viracoocha** [comment]
P.S.  This is my "Edited" version.

[VineTender_Gyges-fix.lua.txt](https://github.com/DashingStrike/Automato-ATITD/files/358421/VineTender_Gyges-fix.lua.txt)

**Comment by ldobson** [comment]
I moved a lot of stuff to OCR, should be more robust. Can you download this file and give it a try?

https://raw.githubusercontent.com/DashingStrike/Automato-ATITD/064a2b5a5bcb6ec8b38bc9e0a4cc724cf9cfa752/scripts/VineTender_Gyges.lua

**Comment by Viracoocha** [comment]
When I have the Tend option selected, it locks up on waiting for window to open.  the window is open.  I unchecked that and left take cutting checked, it took a cutting and closed.  I tried it on named Vines with # in the name.  I don't have any standard vines growing.  Now, in my edits, I had to omit the # symbol to get the old version to work.

**Comment by Viracoocha** [comment]
I am also wondering, while you are working on that script.  Well, I have 2 questions/issues.

1.  Is there a way to do a sendkey(CTRL)
2.  or is there a way to make a regular key act as the jumpoff for vinetender.  IE, instead of pressing ctrl over the vineyard, could we easily change the code to make "!" or "~" or "{" or "[" the keypress that activates vintender.  Reason I ask, I moded Simon, so that I can still Shift click and record the mouse coordinated, BUT, instead of clicking, I have it moving the mouse, and doing a keypress. so while simon moves the mouse from vineyard to vineyard, I don't know how to make it press the ctrl key.  but I do know how to make it press all those other keys,  so either simon doing ctrl presses of simon doing any other pressins and vinetender recognizing that press would work for me.

**Comment by Cegaiel** [comment]
If you view constants.inc , it shows VK_CONTROL that can be used with the srKeyDown event.
To press control, it's be srKeyDown(VK_C); or srKeyDown(0x11); should work, too.

There is also a srKeyDown2/Up2 event that handles it a bit differently.
For example, I wrote a macro that does Alt+C every 15 minutes in ATITD, which takes a screenshot.

I had to mix n match srKeyDown and srKeyEvent to make that work properly.

So, my macro for taking screenshots was like this:

dofile("common.inc");
dofile("constants.inc");

askText = "Presses Alt+C to create .png in ATITD folder";
timer = 900000; --  15 mins

function doit()
	askForWindow(askText);

	while 1 do
	  sleepWithStatus(timer,"Waiting to take screenshot...");
	  srKeyDown2(VK_MENU);
	  lsSleep(100);
	  srKeyEvent('c');
	  lsSleep(100);
	  srKeyUp2(VK_MENU);
	end
end

**Comment by Cegaiel** [comment]
Vines with the # sign in it will now work with commit: https://github.com/DashingStrike/Automato-ATITD/commit/8413be93da8d8308e54f139a310d10c6337c8eee

All issues, on this issue, should be fixed now. The 20-29 in Vigor should properly detect now and vines with # sign, such as Tedra# 13 should be able to be read as well.
